name: Rebuild the CSV from the latest JSON data

on:
  workflow_dispatch:
  schedule:
    - cron:  '13 1 * * *'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install markdown
        pip install markdown-link-attr-modifier
    - name: build
      run: |
        python mitre_attack_csv.py
    - name: push
      uses: actions-x/commit@v2
      with:
        files: annotation_mitre_attack.csv
